services:
  db:
    image: postgres:15-alpine
    container_name: it_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: it_software_mgmt
    ports:
      - "5432:5432" # เปิดเฉพาะ dev
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./apps/db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d it_software_mgmt"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .                # root repo
      dockerfile: ./apps/api/Dockerfile
    container_name: it_backend
    env_file:
      - ./apps/api/.env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: .                # root repo
      dockerfile: ./apps/web/Dockerfile
    container_name: it_frontend
    env_file:
      - ./apps/web/.env
    depends_on:
      - backend
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  db_data: